# Generated by Django 4.2.17 on 2025-01-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edrnsitestreams", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CDEPermissibleValue",
            new_name="DataElementExplorerPermissibleValue",
        ),
    ]
