repos:
    -
        repo: https://github.com/NASA-AMMOS/slim-detect-secrets
        # using commit id for now, will change to tag when official version is released
        rev: 91e097ad4559ae6ab785c883dc5ed989202c7fbe
        hooks:
          - id: detect-secrets
            args:
              - '--baseline'
              - '.secrets.baseline'
              - '--disable-plugin'
              - 'AbsolutePathDetectorExperimental'
              - --exclude-files '\.secrets..*'
              - --exclude-files '\.git.*'
              - --exclude-files '\.mypy_cache'
              - --exclude-files '\.pytest_cache'
              - --exclude-files '\.tox'
              - --exclude-files '\.venv'
              - --exclude-files 'venv'
              - --exclude-files 'dists'
              - --exclude-files 'build'
              - --exclude-files 'static'
              - --exclude-files 'papers'
              - --exclude-files 'media'
              - --exclude-files '__pycache__'
              - --exclude-files '.*\.egg-info'

# Equivalent command-line invocation for generating the baseline:
#
# detect-secrets scan --disable-plugin AbsolutePathDetectorExperimental --exclude-files '\.secrets..*' --exclude-files '\.git.*' --exclude-files '\.mypy_cache' --exclude-files '\.pytest_cache' --exclude-files '\.tox' --exclude-files '\.venv' --exclude-files 'venv' --exclude-files 'dists' --exclude-files 'static' --exclude-files 'papers' --exclude-files 'media' --exclude-files '__pycache__' --exclude-files '.*\.egg-info' > .secrets.baseline
# detect-secrets audit .secrets.baseline
