# Docker Composition for EDRN P5
# ==============================
#
# Sample Docker Composition to support the EDRN Portal, power level 5.


# Services
# --------
#
# Just three are needed for the EDRN portal: an app server (Zope), a database
# (ZEO), and a cache (memcached).
services:
    # EDRN Plone 5-based Portal
    # ~~~~~~~~~~~~~~~~~~~~~~~~~
    #
    # Zope app server running an instance of the Plone portal for EDRN
    edrn-portal:
        container_name: edrn-portal
        # image: docker.pkg.github.com/edrn/p5/edrn-p5:${EDRN_PORTAL_VERSION:-latest}
        # image: nutjob4life/edrn-p5:${EDRN_PORTAL_VERSION:-latest}
        image: edrn-p5:latest
        volumes:
            -
                # Binary large objects or BLOBs; must be same as edrn-db below
                type: bind
                source: ${EDRN_DATA_DIR}/blobstorage
                target: /data/blobstorage
                consistency: consistent
            -
                # This contains Zope logs
                type: bind
                source: ${EDRN_DATA_DIR}/log
                target: /data/log
                consistency: delegated
            # TODO: make the "import" directory available some day
        ports:
            -
                # Map container's Plone's 8080 to 4135 (or EDRN_PUBLISHED_PORT)
                target: 8080
                published: ${EDRN_PUBLISHED_PORT:-4135}
                protocol: tcp
                mode: host
        networks:
            - backplane
            - default
        environment:
            # Empty settings inherit values from the host's environment
            EDRN_PORTAL_VERSION:
            EDRN_DATA_DIR:
            EDRN_PUBLISHED_PORT:
            ZEO_ADDRESS: edrn-db:8080
            ZEO_SHARED_BLOB_DIR: 'on'
        depends_on:
            - edrn-db
            - edrn-memory-cache
        restart: always
        stop_grace_period: 23s
        labels:
            org.label-schema.name: EDRN Public Portal Zope/Plone
            org.label-schema.description: Zope appserver running a Plone instance serving the CMS for the Early Detection Research Network's public portal.

    # EDRN Database (ZEO)
    # ~~~~~~~~~~~~~~~~~~~
    #
    # Zope Enterprise Objects (ZEO) database server
    edrn-db:
        container_name: edrn-db
        image: nutjob4life/edrn-p5:${EDRN_PORTAL_VERSION-latest}
        command: zeo
        volumes:
            -
                # This is the main Zope database; super important!
                type: bind
                source: ${EDRN_DATA_DIR}/filestorage
                target: /data/filestorage
                consistency: consistent
            -
                # Binary large objects or BLOBs; must be same as in edrn-portal above
                type: bind
                source: ${EDRN_DATA_DIR}/blobstorage
                target: /data/blobstorage
                consistency: consistent
            -
                # This contains ZEO logs
                type: bind
                source: ${EDRN_DATA_DIR}/log
                target: /data/log
                consistency: delegated
        networks:
            - backplane
        environment:
            # Empty settings inherit values from the host's environment
            EDRN_PORTAL_VERSION:
        restart: always
        stop_grace_period: 13s
        labels:
            org.label-schema.name: Database
            org.label-schema.description: Zope Enterprise Objects (ZEO) database server for the EDRN Public Portal.

    # Memory Cache
    # ~~~~~~~~~~~~
    #
    # Mainly (exclusively?) for caching LDAP query results
    edrn-memory-cache:
        container_name: edrn-memory-cache
        image: memcached
        networks:
            - backplane
        restart: always
        labels:
            org.label-schema.name: Memory Cache
            org.label-schema.description: Cache for computed objects using `memcached` to speed up the EDRN Public Portal


# Networks
# --------
#
# Thankfully, this is pretty simple.
networks:
    backplane:
        driver: bridge
        labels:
            org.label-schema.name: EDRN P5 Backplane Network
            org.label-schema.description: Internal bridge network so the services that comprise the EDRN Public Portal may communicate.
    default:
        driver: bridge


# Misc
# ----
#
# Only thing we have here is some Docker Compose metadata.
version: '3.7'

