# EDRN P5 - Image Building
# ========================
#
# Used by "docker image build"
#
# Basis
# -----
#
# Used to be based on Plone (Debian) 5.1.5, except that it specifies
# ``VOLUME /data`` and CBIIT demands we run the internal container with
# username "edrn" with user ID 26013. Normally we would just ``adduser`` and
# ``chown`` except thanks to the ``VOLUME /data`` nothing we ``chown`` under
# ``/data`` takes effect and there's no way to undo a basis image's ``VOLUME``
# (see this_). So now we have to reproduce every damn thing the
# ``plone/plone:5.1.5`` image does.
#
# .. _this: https://github.com/moby/moby/issues/3465#issuecomment-45554646
#
# BUT WAIT THERE'S MORE!
#
# The Twit-lock security scanner absolutely hates Debian Linux, so we can't
# base ourselves off the python:2.7 image either, which uses Debian. Further
# tests show that Ubuntu is out too (of course); the only acceptable Linuxes
# are centos:8 and alpine:3. So we either have to install Python, Plone, and
# all our dependencies on centos:8 or use the python:2.7.17-alpine3.11 as a
# base.
#
# That's what follows below.
#
# FURTHER HEADACHE: we can't run as 26013 at JPL or any place else in the
# world because our data volume runs as 500, so let's throw Docker best
# practices out the window and make two images:
#
# ``Dockerfile`` (this file)
#     Makes an image the old fashioned way (user ID 500)
# ``Dockerfile-nci``
#     Makes an image with the user ID 26013 requirement

# Basis
# -----
#
# We'd normally just ue plone:5.2.2 but see the "diatribe" above.

FROM python:2.7.17-alpine3.11


# Versions and digests
# --------------------
#
# The urllib3 is to get around a Twit-lock security flag
# And urllib3 1.25.7 → 1.25.9 is another Twit-lock security flag
# And urllib3 1.25.9 → 1.26.6 for yet another Twit-lock security issue

ENV \
    URLLIB3=1.26.6 \
    PIP=19.2 \
    ZC_BUILDOUT=2.12.1 \
    SETUPTOOLS=39.1.0 \
    WHEEL=0.31.1 \
    PLONE_MAJOR=5.2 \
    PLONE_VERSION=5.2.2 \
    PLONE_VERSION_RELEASE=Plone-5.2.2-UnifiedInstaller \
    PLONE_MD5=a603eddfd3abb0528f0861472ebac934 \
    UNDERSCORE_TARBALL=https://github.com/jashkenas/underscore/archive/refs/tags/1.12.1.tar.gz


# Plone and EDRN Setup
# --------------------
#
# OK, now that we have a working Python, let's change it up.
#
# Users and Directories
# ~~~~~~~~~~~~~~~~~~~~~
#
# See note above; for NCI we change to 26013 instead of 500

RUN : &&\
    addgroup -S -g 26013 edrn &&\
    adduser -S -D -h /plone -G edrn -u 26013 -g 'Plone for EDRN User' edrn &&\
    mkdir -p /plone/instance /data/filestorage /data/blobstorage


# Our Code
# ~~~~~~~~
#
# The ``etc`` and ``src`` directories are our own, as is the ``docker.cfg``;
# the ``buildout.cfg`` is duplicated from plone/plone.docker, as is the
# ``docker-initialize.py`` and the (modified) ``docker-entrypoint.sh``.

COPY --chown=edrn:edrn buildout.cfg docker.cfg /plone/instance/
COPY --chown=edrn:edrn etc /plone/instance/etc
COPY --chown=edrn:edrn src /plone/instance/src
COPY --chown=edrn:edrn patches /plone/instance/patches
COPY docker-initialize.py docker-entrypoint.sh /


# Buildout
# ~~~~~~~~
#
# Now we build everything out. This is a big layer! Be patient, it downloads,
# installs, extracts, compiles, and more.

RUN : &&\
    echo '@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories &&\
    echo '@edge http://dl-cdn.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories &&\
    apk update &&\
    : More Twit-lock &&\
    apk del tiff &&\
    : We will uninstall these later &&\
    buildDeps="patch gcc bzip2-dev musl-dev libjpeg-turbo-dev openjpeg-dev pcre-dev openssl-dev tiff-dev libxml2-dev libxslt-dev zlib-dev cyrus-sasl-dev libffi-dev" &&\
    apk add --virtual plone-build $buildDeps &&\
    : These stay &&\
    runDeps="curl krb5-libs@edge openjpeg@edge openldap-dev libldap@edge libsasl libjpeg-turbo tiff libxml2 libxslt lynx netcat-openbsd libstdc++@edge libgcc@edge sqlite-libs@edge poppler-utils@edge rsync wv su-exec bash" &&\
    apk add $runDeps &&\
    cp /plone/instance/etc/certs/EntrustPublic_Intermediate.crt /usr/local/share/ca-certificates &&\
    update-ca-certificates &&\
    :

RUN : &&\
    : Get, check, and extract Plone &&\
    wget -q -O Plone.tgz https://launchpad.net/plone/$PLONE_MAJOR/$PLONE_VERSION/+download/$PLONE_VERSION_RELEASE.tgz &&\
    echo "$PLONE_MD5  Plone.tgz" | md5sum -c - &&\
    tar -xzf Plone.tgz &&\
    cp -r ./$PLONE_VERSION_RELEASE/base_skeleton/* /plone/instance/ &&\
    cp /plone/instance/etc/versions/release-5.2.3-versions.cfg /plone/instance &&\
    rm -rf \
        /plone/buildout-cache/eggs/plone.staticresources-1.3.2-py2.7.egg \
        /plone/buildout-cache/eggs/Zope-4.5.1-py2.7.egg \
        /plone/buildout-cache/eggs/plone.recipe.zope2instance-6.7.5-py2.7.egg \
        /plone/buildout-cache/eggs/zope.interface-5.0.2-py2.7-linux-x86_64.egg \
        /plone/buildout-cache/eggs/Products.MailHost-4.9-py2.7.egg \
        /plone/buildout-cache/eggs/calmjs.parse-1.2.4-py2.7.egg \
        /plone/buildout-cache/eggs/icalendar-4.0.6-py2.7.egg \
        /plone/buildout-cache/eggs/mockup-3.2.2-py2.7.egg \
        /plone/buildout-cache/eggs/plone.api-1.10.2-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.caching-2.0.6-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.content-3.8.6-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.contentlisting-2.0.2-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.contentrules-4.1.4-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.contenttypes-2.1.10-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.dexterity-2.6.5-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.discussion-3.4.2-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.event-3.2.7-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.iterate-3.3.14-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.layout-3.4.4-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.linkintegrity-3.3.13-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.locales-5.1.24-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.multilingual-5.6.1-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.portlets-4.4.5-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.registry-1.7.6-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.textfield-1.3.4-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.theming-4.1.4-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.upgrade-2.0.34-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.vocabularies-4.2.0-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.widgets-3.0.4-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.workflow-4.0.2-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.z3cform-3.2.2-py2.7.egg \
        /plone/buildout-cache/eggs/plone.behavior-1.3.2-py2.7.egg \
        /plone/buildout-cache/eggs/plone.contentrules-2.0.10-py2.7.egg \
        /plone/buildout-cache/eggs/plone.dexterity-2.9.7-py2.7.egg \
        /plone/buildout-cache/eggs/plone.keyring-3.1.2-py2.7.egg \
        /plone/buildout-cache/eggs/plone.outputfilters-4.0.1-py2.7.egg \
        /plone/buildout-cache/eggs/plone.portlet.collection-3.3.3-py2.7.egg \
        /plone/buildout-cache/eggs/plone.protect-4.1.5-py2.7.egg \
        /plone/buildout-cache/eggs/plone.resource-2.1.2-py2.7.egg \
        /plone/buildout-cache/eggs/plone.restapi-6.2.0-py2.7.egg \
        /plone/buildout-cache/eggs/plone.resourceeditor-3.0.2-py2.7.egg \
        /plone/buildout-cache/eggs/plone.schemaeditor-3.0.1-py2.7.egg \
        /plone/buildout-cache/eggs/plone.stringinterp-1.3.2-py2.7.egg \
        /plone/buildout-cache/eggs/plone.subrequest-1.9.2-py2.7.egg \
        /plone/buildout-cache/eggs/plone.supermodel-1.6.2-py2.7.egg \
        /plone/buildout-cache/eggs/plonetheme.barceloneta-2.1.9-py2.7.egg \
        /plone/buildout-cache/eggs/Products.CMFDiffTool-3.3.1-py2.7.egg \
        /plone/buildout-cache/eggs/Products.CMFFormController-4.1.2-py2.7.egg \
        /plone/buildout-cache/eggs/Products.CMFPlacefulWorkflow-2.0.2-py2.7.egg \
        /plone/buildout-cache/eggs/Plone-5.2.2-py2.7.egg \
        /plone/buildout-cache/eggs/Products.CMFPlone-5.2.2-py2.7.egg \
        /plone/buildout-cache/eggs/Products.CMFUid-3.0.2-py2.7.egg \
        /plone/buildout-cache/eggs/Products.ExtendedPathIndex-4.0.0-py2.7.egg \
        /plone/buildout-cache/eggs/Products.ExternalEditor-3.0-py2.7.egg \
        /plone/buildout-cache/eggs/Products.GenericSetup-2.0.2-py2.7.egg \
        /plone/buildout-cache/eggs/Products.isurlinportal-1.1.0-py2.7.egg \
        /plone/buildout-cache/eggs/Products.MimetypesRegistry-2.1.7-py2.7.egg \
        /plone/buildout-cache/eggs/Products.PluggableAuthService-2.4-py2.7.egg \
        /plone/buildout-cache/eggs/Products.PortalTransforms-3.1.8-py2.7.egg \
        /plone/buildout-cache/eggs/Products.Sessions-4.6-py2.7.egg \
        /plone/buildout-cache/eggs/z3c.form-3.7.0-py2.7.egg \
        /plone/buildout-cache/eggs/plone.app.relationfield-2.0.2-py2.7.egg \
        /plone/buildout-cache/eggs/z3c.jbot-0.8-py2.7.egg &&\
    sed -e 's/5\.2\.2/5.2.3/g' ./$PLONE_VERSION_RELEASE/buildout_templates/buildout.cfg > /plone/instance/buildout-base.cfg &&\
    : Clean up anything copied from our src dirs &&\
    find /plone/instance/src -name '*.py[co]' -exec rm -f '{}' + &&\
    rm -rf /plone/instance/src/*/{var,bin,develop-eggs,parts} &&\
    : Install buildout, setuptools, and pip at specific versions &&\
    pip --quiet install pip==$PIP setuptools==$SETUPTOOLS zc.buildout==$ZC_BUILDOUT wheel==$WHEEL urllib3==$URLLIB3 &&\
    :

RUN : &&\
    cd /plone/instance &&\
    buildout &&\
    :

RUN : &&\
    buildout -c docker.cfg &&\
    :

RUN : &&\
    : apk ghetto-up &&\
    find /plone/buildout-cache/eggs/plone.staticresources-1.4.1-py2.7.egg/plone/staticresources/static -type f -exec sed -i -e 's/1\.10\.16/1.10.22/g' '{}' \; &&\
    :

RUN : &&\
    ln -s /data/filestorage/ /plone/instance/var/filestorage &&\
    ln -s /data/blobstorage /plone/instance/var/blobstorage &&\
    :

RUN : &&\
    chown -R edrn:edrn /plone /data &&\
    rm -rf /Plone* &&\
    :


# Twit-Lock
# ---------

RUN : &&\
    rm \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/BlpImagePlugin.pyc \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/BlpImagePlugin.py \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/BlpImagePlugin.pyo \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/IcnsImagePlugin.pyc \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/IcnsImagePlugin.py \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/IcnsImagePlugin.pyo \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/IcoImagePlugin.pyc \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/IcoImagePlugin.py \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/IcoImagePlugin.pyo \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/FliImagePlugin.pyc \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/FliImagePlugin.py \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/FliImagePlugin.pyo \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/Jpeg2KImagePlugin.pyc \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/Jpeg2KImagePlugin.py \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/Jpeg2KImagePlugin.pyo \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/SgiImagePlugin.pyc \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/SgiImagePlugin.py \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/SgiImagePlugin.pyo \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/TiffImagePlugin.pyo \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/PcxImagePlugin.py \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/PcxImagePlugin.pyc \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/PcxImagePlugin.pyo \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/EpsImagePlugin.py \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/EpsImagePlugin.pyc \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/EpsImagePlugin.pyo \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/ImageColor.pyc \
        /plone/buildout-cache/eggs/Pillow-6.2.2-py2.7-linux-x86_64.egg/PIL/ImageColor.pyo &&\
    patch -p0 </plone/instance/patches/pil.patch &&\
    apk del plone-build &&\
    apk add apk-tools@edge busybox@edge ncurses-libs@edge ncurses-terminfo-base@edge &&\
    curl --silent --location $UNDERSCORE_TARBALL | tar x -f - -C /tmp -z underscore-1.12.1/underscore.js underscore-1.12.1/underscore-min.js &&\
    cp /tmp/underscore-1.12.1/underscore-min.js /plone/buildout-cache/eggs/plone.staticresources-1.4.1-py2.7.egg/plone/staticresources/static/components/underscore &&\
    cp /tmp/underscore-1.12.1/underscore.js /plone/buildout-cache/eggs/plone.staticresources-1.4.1-py2.7.egg/plone/staticresources/static/components/underscore &&\
    cp /tmp/underscore-1.12.1/underscore.js /plone/buildout-cache/eggs/plone.staticresources-1.4.1-py2.7.egg/plone/staticresources/static/components/backbone.paginator/examples/libs &&\
    rm -rf /tmp/underscore-1.12.1 &&\
    /usr/local/bin/pip install --upgrade pip==$PIP &&\
    rm -rf /plone/instance/patches &&\
    rm -rf /plone/buildout-cache/downloads/* /var/cache/apk/* &&\
    :


# Context
# -------
#
# Finally, we set up the runtime context: volume, cwd, etc.

VOLUME      /data
EXPOSE      8080
USER        edrn:edrn
WORKDIR     /plone/instance
HEALTHCHECK --interval=5m --timeout=2m --start-period=1m CMD curl --fail --retry 6 --max-time 5 --retry-delay 10 --retry-max-time 60 http://127.0.0.1:8080/ || sh -c 'killall5 -TERM && (sleep 10; killall5 -KILL)'
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD        ["start"]


# Metadata
# --------
#
# Note that ``org.label-schema`` is deprecated, but it's a heck of a lot
# easier to understand.  Still, I have to wonder why they didn't just use
# Dublin Core.

LABEL "org.label-schema.name"="EDRN Public Portal Power Level 5"
LABEL "org.label-schema.description"="Plone 5-based portal for the Early Detecton Research Network"
LABEL "org.label-schema.version"="5.0.0"
LABEL "org.label-schema.schema-version"="1.0"
LABEL "org.label-schema.docker.cmd"="docker run --detach --publish 2345:8080 --volume ${EDRN_DATA_DIR}/filestorage:/data/filestorage --volume ${EDRN_DATA_DIR}/blobstorage:/data/blobstorage --volume ${EDRN_DATA_DIR}/log:/data/log edrn-p5"


# Dependencies
# ------------
#
# To figure this out, first set up a throwaway Debian container and run::
#     apt-get update
#     apt-get install apt-file
#     apt-file update
# Then for a package X::
#     apt-get install X
#     apt-file list X
# And pick a sentinel file from the list. Plug that into https://pkgs.alpinelinux.org/contents
# to find out what Alpine package provides that file.
#
# Key: debian-package sentinel-file alpine-package
#
# Build Time
# ~~~~~~~~~~
#
# From Plone's Dockerfile:
# gcc                   /usr/bin/gcc            gcc
# libbz2-dev            /usr/include/bzlib.h                    bzip2-dev
# libc6-dev             /usr/include/signal.h                   musl-dev
# libjpeg62-turbo-dev   /usr/include/jerror.h                   libjpeg-turbo-dev
# libopenjp2-7-dev      /usr/include/openjpeg-2.3/openjpeg.h    openjpeg-dev
# libpcre3-dev          /usr/include/pcre.h                     pcre-dev
# libssl-dev            /usr/include/openssl/ssl.h              openssl-dev
# libtiff5-dev          "transitional package"; try tiff.h      tiff-dev
# libxml2-dev           /usr/bin/xml2-config                    libxml2-dev
# libxslt1-dev          /usr/bin/xslt-config                    libxslt-dev
# wget                  /usr/bin/wget                           wget (is this really build dep?)*
# zlib1g-dev            /usr/include/zlib.h                     zlib-dev
#
# Implicit deps:
# libffi-dev            /usr/include/x86_64-linux-gnu/ffi.h     libffi-dev
#
# ALSO: wget is BusyBox! Do we need the full wget?
# dpkg-dev?
#
# Our own additional needs for P5:
#
# libldap2-dev          /usr/include/ldap.h                     openldap-dev
# libsasl2-dev          /usr/include/sasl/sasl.h                cyrus-sasl-dev
#
# Run Time
# ~~~~~~~~
#
# gosu                  /usr/sbin/gosu                          gosu@testing
# libjpeg62             libjpeg.so                              libjpeg-turbo
# libopenjp2-7          libopenjp2.so                           openjpeg
# libtiff5              libtiff.so                              tiff
# libxml2               libxml2.so                              libxml2
# libxslt1.1            libxslt.so                              libxslt
# lynx                  /usr/bin/lynx                           lynx
# netcat (virtual)      /usr/bin/nc                             netcat-openbsd
# poppler-utils         /usr/bin/pdftohtml                      poppler-utils@edge
# rsync                 /usr/bin/rsync                          rsync
# wv                    /usr/bin/wvHtml                         wv


