# Generated by Django 4.0.6 on 2022-07-17 01:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('h', 'Header'), ('b', 'Bottom')], default='b', help_text='Where to inject this; in the <head> or at the bottom before the closing </body>', max_length=1)),
                ('code', models.TextField(default='<script></script>', help_text='JavaScript analytics code')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text="URL to NCI's Facebook page")),
                ('twitter', models.URLField(blank=True, help_text="URL to DCP's Twitter profile")),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_per_page', models.IntegerField(default=20, help_text='How many hits to show per page on search', validators=[django.core.validators.MinValueValidator(1)])),
                ('orphans', models.IntegerField(default=3, help_text='How many orphans to avoid having on a lone search page', validators=[django.core.validators.MinValueValidator(0)])),
                ('surrounding', models.IntegerField(default=3, help_text='How many pages to show surrounding the active page in search pagination outside of elision', validators=[django.core.validators.MinValueValidator(0)])),
                ('ends', models.IntegerField(default=2, help_text='How many pages to show at the start and end of search pagination regardless of elision', validators=[django.core.validators.MinValueValidator(0)])),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Informatics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_development', models.BooleanField(default=True, help_text='True if this site is in development')),
                ('entrez_email', models.EmailField(default='sean.kelly@nih.gov', help_text='Entrez registered user email', max_length=254)),
                ('entrez_id', models.CharField(default='edrn-portal', help_text='Entrez (PubMed API) tool identification', max_length=64)),
                ('dmcc_url', models.URLField(default='https://www.compass.fhcrc.org/enterEDRN/?cl=3&amp;dl=0.9&amp;param1=dmcc&amp;extra_param=plin', help_text='URL to the DMCC "secure site"')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
