# Generated by Django 4.1.9 on 2023-09-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontrols', '0002_informatics_entrez_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='informatics',
            name='funding_cycle',
            field=models.CharField(default='Ⅴ', help_text='EDRN Funding Cycle', max_length=8),
        ),
    ]
