# Generated by Django 4.1.9 on 2023-10-02 17:32

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontrols', '0003_informatics_funding_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='informatics',
            name='site_wide_banner',
            field=wagtail.fields.RichTextField(blank=True, help_text='Banner to display site-wide at the top of every page'),
        ),
    ]
