# Generated by Django 4.2.7 on 2023-12-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edrnsitecontrols", "0004_informatics_site_wide_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmedia",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="socialmedia",
            name="site",
        ),
        migrations.RemoveField(
            model_name="socialmedia",
            name="twitter",
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="bootstrap_icon",
            field=models.CharField(
                default="emoji-smile",
                help_text="Name of the icon to signify this site",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="enabled",
            field=models.BooleanField(
                default=True, help_text="Whether to include this in the footer"
            ),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="name",
            field=models.CharField(
                default="name",
                help_text="Name of the social media site",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="url",
            field=models.URLField(
                default="https://site", help_text="Link to EDRN's presence on this site"
            ),
        ),
    ]
