# Generated by Django 4.2.7 on 2023-12-11 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "edrnsitecontrols",
            "0005_remove_socialmedia_facebook_remove_socialmedia_site_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SocialMedia",
            new_name="SocialMediaLink",
        ),
    ]
