# Generated by Django 4.2.10 on 2024-07-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edrnsitecontrols", "0006_rename_socialmedia_socialmedialink"),
    ]

    operations = [
        migrations.AddField(
            model_name="informatics",
            name="ip_address",
            field=models.CharField(
                default="unknown",
                help_text="Last known source IP address of the portal",
                max_length=40,
            ),
        ),
    ]
