# Generated by Django 4.2.10 on 2024-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edrnsitecontrols", "0007_informatics_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="informatics",
            name="ip_address_service",
            field=models.URLField(
                default="https://api.ipify.org",
                help_text="API endpoint of IP address service",
            ),
        ),
    ]
