# Generated by Django 4.2.14 on 2024-08-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edrnsitecontrols", "0008_informatics_ip_address_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="informatics",
            name="override_version",
            field=models.CharField(
                default="",
                help_text="Version number to override in footer; blank determines from software",
            ),
        ),
    ]
