# Generated by Django 4.2.20 on 2025-05-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edrnsitecontrols", "0010_alter_informatics_override_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="bedrock_access_key",
            field=models.CharField(
                default="key", help_text="AWS Access Key for Bedrock", max_length=192
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="bedrock_secret_key",
            field=models.CharField(
                default="key",
                help_text="AWS Secret Access Key for Bedrock",
                max_length=192,
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="system_prompt",
            field=models.CharField(
                default="You are a search assistant for the Early Detection Research network",
                help_text="System prompt to present for search result summaries",
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="user_prompt_prefix",
            field=models.CharField(
                default="Summarize the following search results:",
                help_text="User prompt to prefix before the search results to be summarized",
                max_length=1000,
            ),
        ),
    ]
