# Generated by Django 4.2.20 on 2025-05-01 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edrnsitecontrols",
            "0011_search_bedrock_access_key_search_bedrock_secret_key_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="bedrock_model",
            field=models.CharField(
                default="amazon.titan-text-express-v1",
                help_text="Bedrock AI model to use",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="when_to_enable_ai",
            field=models.IntegerField(
                default=0,
                help_text="How many search results there must be to offer AI summary; user zero to disable AI",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
