# Generated by Django 4.2.20 on 2025-05-01 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edrnsitecontrols", "0012_search_bedrock_model_search_when_to_enable_ai"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search",
            name="when_to_enable_ai",
            field=models.IntegerField(
                default=0,
                help_text="How many search results there must be to offer AI summary; zero will always use AI while -1 will turn it off",
                validators=[django.core.validators.MinValueValidator(-1)],
            ),
        ),
    ]
