# Generated by Django 4.2.20 on 2025-05-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edrnsitecontrols", "0013_alter_search_when_to_enable_ai"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="bedrock_region",
            field=models.CharField(
                default="us-west-2", help_text="AWS data center region", max_length=12
            ),
        ),
    ]
