# Generated by Django 4.2.20 on 2025-05-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edrnsitecontrols", "0014_search_bedrock_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="search",
            name="bedrock_model",
        ),
        migrations.RemoveField(
            model_name="search",
            name="user_prompt_prefix",
        ),
        migrations.AlterField(
            model_name="search",
            name="system_prompt",
            field=models.CharField(
                default="Act as a search assistant for the Early Detection Research Network, summarizing voluminous search results into easily digestible summaries.",
                help_text="System prompt to present for search result summaries",
                max_length=1000,
            ),
        ),
    ]
