# Generated by Django 4.0.5 on 2022-06-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeGroupSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cg_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Collaborative Group Snippet',
                'verbose_name_plural': 'Collaborative Group Snippets',
            },
        ),
    ]
