# Generated by Django 4.1.4 on 2022-12-15 21:52

from django.db import migrations, models
import django.db.models.deletion
import edrnsite.streams.blocks
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ekeknowledge', '0002_committeeindex'),
        ('wagtailcore', '0077_alter_revision_user'),
        ('edrncollabgroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeEvent',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('when', models.DateTimeField(help_text='When does this event start; will be converted to UTC based on timezone below')),
                ('timezone', models.CharField(choices=[('America/Los_Angeles', 'Los Angeles (pacific)'), ('America/Denver', 'Denver (mountain)'), ('America/Chicago', 'Chicago (central)'), ('America/New_York', 'New York (eastern)'), ('UTC', 'UTC (global)')], default='America/New_York', help_text='Timezone of this event', max_length=19)),
                ('online_meeting_url', models.URLField(blank=True, help_text='URL to online event; please remove any "URL-defense" before pasting in a URL')),
                ('body', wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock(help_text='Richly formatted text', icon='doc-full', label='Rich Text')), ('cards', wagtail.blocks.StructBlock([('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title of this card, max 100 chars', max_length=100))])))])), ('table', edrnsite.streams.blocks.TableBlock()), ('carousel', wagtail.blocks.StructBlock([('media', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('label', wagtail.blocks.CharBlock(help_text='Overlaid label, if any', max_length=120, required=False)), ('caption', wagtail.blocks.CharBlock(help_text='Overlaid caption, if any', max_length=400, required=False))])))]))], blank=True, help_text='Body text of this event', null=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('id_number', models.CharField(blank=True, help_text='DMCC-assigned identification number', max_length=10)),
                ('description', models.TextField(blank=True, help_text='A summary or descriptive abstract')),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees_I_chair', to='ekeknowledge.person', verbose_name='Chair')),
                ('co_chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees_I_co_chair', to='ekeknowledge.person', verbose_name='Co-Chair')),
                ('members', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='committees_I_belong_to', to='ekeknowledge.person', verbose_name='Members')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
