# Generated by Django 4.2.6 on 2023-11-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrncollabgroups', '0002_committeeevent_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='nci_program_director',
            field=models.CharField(blank=True, help_text='Optional name of the director of this program at NCI', max_length=120),
        ),
    ]
