# Generated by Django 4.2.7 on 2023-11-08 19:26

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ekeknowledge', '0014_alter_person_photo'),
        ('edrncollabgroups', '0003_committee_nci_program_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='nci_program_director',
        ),
        migrations.AddField(
            model_name='committee',
            name='program_officers',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='committees_I_officiate', to='ekeknowledge.person', verbose_name='Program Officers'),
        ),
        migrations.AddField(
            model_name='committee',
            name='project_scientists',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='committess_I_do_science_for', to='ekeknowledge.person', verbose_name='Project Scientists'),
        ),
    ]
