# Generated by Django 4.2.7 on 2024-01-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edrncollabgroups", "0004_remove_committee_nci_program_director_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="documents_heading",
            field=models.TextField(
                default="Documents",
                help_text="What should the heading above the documents/agendas be?",
            ),
        ),
    ]
