# Generated by Django 4.2.20 on 2025-04-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edrncollabgroups", "0006_remove_committee_co_chair_committee_co_chairs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeeevent",
            name="online_meeting_url",
            field=models.URLField(
                blank=True,
                help_text='URL to online event; please remove any "URL-defense" before pasting in a URL',
                max_length=2000,
            ),
        ),
    ]
