# Generated by Django 4.2.20 on 2025-04-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edrncollabgroups", "0007_alter_committeeevent_online_meeting_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="committeeevent",
            name="duration",
            field=models.IntegerField(
                default=60, help_text="How long the event is, in minutes"
            ),
        ),
    ]
