# Buildout and Test Action
# ========================
#
# GitHub action that:
# • Bootstraps a zc.buildout 
# • Runs the buildout, which we assume makes a zope testrunner
# • RUns the test runner

---

name: 'Buildout'
author: 'Sean Kelly <kelly@seankelly.biz>'
description: 'Bootstrap and run a zc.buildout and then tests'
branding:
    # Quite possibly the best icon:
    icon: 'meh'
    color: 'purple'
inputs:
    bootstrap-url:
        description: >
            URL to the bootstrapper to use; only used if the repository lacks `bootstrap.py` and defaults to
            zc.buildout's web master file
        required: false
        default: 'https://bootstrap.pypa.io/bootstrap-buildout.py'
    buildout-config:
        description: >
            Path within the GitHub workspace of the zc.buildout configuration to use, if any; defaults to
            `buildout.cfg`.
        required: false
        default: 'buildout.cfg'
    test-packages:
        description: >
            Test packages to run
        required: true
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.bootstrap-url }}
        - ${{ inputs.buildout-config }}
        - ${{ inputs.test-packages }}

...
