# Generated by Django 4.1.4 on 2022-12-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekeknowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeIndex',
            fields=[
                ('knowledgefolder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ekeknowledge.knowledgefolder')),
            ],
            options={
                'abstract': False,
            },
            bases=('ekeknowledge.knowledgefolder',),
        ),
    ]
