# Generated by Django 4.1.7 on 2023-03-05 00:12

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('ekeknowledge', '0002_committeeindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalGroup',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='person',
            name='degrees',
            field=models.CharField(blank=True, help_text='Academia', max_length=40),
        ),
        migrations.CreateModel(
            name='OrgGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_name', models.CharField(blank=True, help_text='Organ(s)', max_length=120)),
                ('group_num', models.IntegerField(default=0, help_text='Group Number')),
                ('sort_order', models.IntegerField(default=0, help_text='Sort Order')),
                ('member_type', models.CharField(blank=True, help_text='Member type(s)', max_length=30)),
                ('role', models.CharField(blank=True, help_text='Role played', max_length=30)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='ekeknowledge.organizationalgroup')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ekeknowledge.person', verbose_name='Principal Investigator')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ekeknowledge.site', verbose_name='Site')),
            ],
            options={
                'ordering': ['organ_name', 'group_num', 'sort_order', 'pi__title'],
            },
        ),
    ]
