# Generated by Django 4.1.7 on 2023-03-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekeknowledge', '0003_organizationalgroup_person_degrees_orggroupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='kind',
            field=models.CharField(blank=True, help_text='Protocol type', max_length=80),
        ),
    ]
