# Generated by Django 4.1.7 on 2023-03-14 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontent', '0007_rename_capchaemailform_captchaemailform_and_more'),
        ('ekeknowledge', '0004_protocol_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollectionindex',
            name='metadata_collection_form',
            field=models.ForeignKey(blank=True, help_text='Which page to use as the metadata collection form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edrnsitecontent.metadatacollectionformpage', verbose_name='Metadata Collection Form'),
        ),
    ]
