# Generated by Django 4.1.9 on 2023-08-03 18:46

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ekeknowledge', '0007_publicationsubjecturi'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='publications',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='site_that_wrote_this', to='ekeknowledge.publication', verbose_name='Publications made by this site'),
        ),
    ]
