# Generated by Django 4.1.9 on 2023-09-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekeknowledge', '0008_site_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='dataSharingPolicy',
            field=models.CharField(blank=True, help_text='When was the data sharing policy made', max_length=30),
        ),
    ]
