# Generated by Django 4.1.9 on 2023-09-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekeknowledge', '0010_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='value',
            new_name='description',
        ),
    ]
