# Generated by Django 4.1.9 on 2023-09-14 09:35

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ekeknowledge', '0011_rename_value_interest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollectionindex',
            name='preamble',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to appear at the top of the page'),
        ),
    ]
