# Generated by Django 4.2.7 on 2023-11-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('ekeknowledge', '0014_alter_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberFinderPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            bases=('wagtailcore.page',),
        ),
    ]
