# Generated by Django 4.2.10 on 2024-03-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ekeknowledge", "0017_protocol_estimated_finish_date_protocol_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="outcome",
            field=models.TextField(
                blank=True, help_text="What this protocol's net result was"
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="secure_outcome",
            field=models.TextField(
                blank=True, help_text="What this protocol's secret net result was"
            ),
        ),
    ]
