# Generated by Django 4.2.16 on 2024-11-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ekeknowledge", "0019_remove_protocol_fieldofresearch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="pis",
            field=models.CharField(
                blank=True, help_text="EDRN PIs who wrote this", max_length=250
            ),
        ),
    ]
