# Generated by Django 4.2.16 on 2024-11-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ekeknowledge", "0020_publication_pis"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="month",
            field=models.CharField(
                blank=True, help_text="Month of publication", max_length=10
            ),
        ),
    ]
