# Generated by Django 4.2.16 on 2024-11-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ekeknowledge", "0021_publication_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="month",
            field=models.CharField(
                blank=True, help_text="Month of publication", max_length=16
            ),
        ),
    ]
