# Generated by Django 5.2.10 on 2026-01-07 15:44

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ekeknowledge", "0023_knowledgeobjectlogentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForbiddenPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="PubMed ID (Entrez Medline ID code number) of forbidden publication",
                        max_length=20,
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forbidden_publications",
                        to="ekeknowledge.publicationindex",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
