# Generated by Django 5.2.11 on 2026-07-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ekebiomarkers", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomarkerindex",
            name="five_phase_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Which page to use as the link for the Five Phase page",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Five phase page",
            ),
        ),
    ]
