# Generated by Django 4.1.7 on 2023-03-08 18:46

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('edrnsitecontent', '0006_metadatacollectionformpage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapchaEmailForm',
            new_name='CaptchaEmailForm',
        ),
        migrations.AddField(
            model_name='specimenreferencesetrequestformpage',
            name='proposal_advice',
            field=wagtail.fields.RichTextField(blank=True, help_text='Enter the advice on filling out the "Scientific Proposal" section.'),
        ),
    ]
