# Generated by Django 4.1.7 on 2023-04-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontent', '0007_rename_capchaemailform_captchaemailform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenreferencesetrequestformpage',
            name='submitter_closing',
            field=models.TextField(default='\nFor your reference, a copy of your proposal is attached. If you have any\nquestions or concerns, please reach out to the DMCC by replying to this\nmessage or emailing directly to edrndmcc@fredhutch.org.\n', help_text='Closing to the message body for the copy of the form data sent to the submitter of the request'),
        ),
        migrations.AddField(
            model_name='specimenreferencesetrequestformpage',
            name='submitter_from',
            field=models.EmailField(default='edrndmcc@fredhutch.org', help_text="Email address from which to send the copy of the form data that's sent to the submitter of the request", max_length=254),
        ),
        migrations.AddField(
            model_name='specimenreferencesetrequestformpage',
            name='submitter_preamble',
            field=models.TextField(default='\nThank you for your specimen reference set request. This email can serve as a\nreceipt for your request should you need to refer back to it in the future. It\nis also a reminder of the affirmations you made as part of the request.\n\nFor your information, here are those affirmations and your typed "signature":\n', help_text='Preamble to the message body for the copy of the form data sent to the submitter of the request'),
        ),
        migrations.AddField(
            model_name='specimenreferencesetrequestformpage',
            name='submitter_subject',
            field=models.CharField(default='A copy of your specimen reference set request, for your records', help_text='Subject line for the copy of the form sent to the submitter of the request', max_length=80),
        ),
    ]
