# Generated by Django 4.1.7 on 2023-05-04 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('edrnsitecontent', '0010_datasetmetadataformpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostmanAPIPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('postman', models.TextField(help_text='Postman JSON Export')),
                ('swagger', models.TextField(help_text='OpenAPI YAML Conversion')),
                ('postmanerator', models.TextField(blank=True, help_text='Postmanerator documentation using EDRN Portal Theme')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TaxonomyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('taxonomy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomy_page', to='wagtaildocs.document', verbose_name='Taxonomy JavaScript file')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
