# Generated by Django 4.1.9 on 2023-06-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontent', '0016_metadataobject_metadataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeexplorerpage',
            name='demo_mode',
            field=models.CharField(choices=[('compact', 'Compact'), ('full', 'Full')], default='compact', max_length=7),
        ),
    ]
