# Generated by Django 4.1.9 on 2023-07-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('edrnsitecontent', '0017_treeexplorerpage_demo_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDEExplorerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Name of this common data element', max_length=100)),
                ('definition', models.TextField(blank=True, help_text='A thorough definition of this CDE')),
                ('required', models.CharField(blank=True, help_text='Required, not, or something else?', max_length=50)),
                ('data_type', models.CharField(blank=True, help_text='Kind of data', max_length=30)),
                ('explanatory_note', models.TextField(blank=True, help_text='Note helping explain use of the CDE')),
            ],
        ),
        migrations.CreateModel(
            name='CDEExplorerObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this object in a CDE hierarchy', max_length=200)),
                ('description', models.TextField(blank=True, help_text='A nice long description of this object')),
                ('attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_described', to='edrnsitecontent.cdeexplorerattribute')),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='edrnsitecontent.cdeexplorerobject')),
            ],
        ),
        migrations.CreateModel(
            name='CDEPermissibleValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='An enumerated value allowed for a data element that uses permissible values', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CDEExplorerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('last_update_log', models.TextField(blank=True, help_text='Log of how well the last update went')),
                ('root_objects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explorer', to='edrnsitecontent.cdeexplorerobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='cdeexplorerattribute',
            name='permissible_values',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_attribute', to='edrnsitecontent.cdepermissiblevalue'),
        ),
    ]
