# Generated by Django 4.1.9 on 2023-07-19 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontent', '0018_cdeexplorerattribute_cdeexplorerobject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdeexplorerattribute',
            name='permissible_values',
        ),
        migrations.RemoveField(
            model_name='cdeexplorerobject',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='cdeexplorerpage',
            name='root_objects',
        ),
        migrations.AddField(
            model_name='cdeexplorerattribute',
            name='obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='edrnsitecontent.cdeexplorerobject'),
        ),
        migrations.AddField(
            model_name='cdeexplorerobject',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_objects', to='edrnsitecontent.cdeexplorerpage'),
        ),
        migrations.AddField(
            model_name='cdepermissiblevalue',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissible_values', to='edrnsitecontent.cdeexplorerattribute'),
        ),
        migrations.AlterField(
            model_name='cdeexplorerobject',
            name='children',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='edrnsitecontent.cdeexplorerobject'),
        ),
    ]
