# Generated by Django 4.1.9 on 2023-07-19 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontent', '0019_remove_cdeexplorerattribute_permissible_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdeexplorerobject',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='edrnsitecontent.cdeexplorerobject'),
        ),
    ]
