# Generated by Django 4.1.9 on 2023-07-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontent', '0020_alter_cdeexplorerobject_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdeexplorerobject',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_objects', to='edrnsitecontent.cdeexplorerpage'),
        ),
    ]
