# Generated by Django 4.1.9 on 2023-07-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontent', '0022_remove_cdeexplorerobject_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdeexplorerobject',
            name='children',
        ),
        migrations.AddField(
            model_name='cdeexplorerobject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='edrnsitecontent.cdeexplorerobject'),
        ),
    ]
