# Generated by Django 4.1.9 on 2023-07-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontent', '0024_cdeexplorerpage_spreadsheet_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdeexplorerpage',
            old_name='last_update_log',
            new_name='update_log',
        ),
        migrations.RemoveField(
            model_name='cdeexplorerpage',
            name='spreadsheet_url',
        ),
        migrations.AddField(
            model_name='cdeexplorerpage',
            name='spreadsheet_id',
            field=models.CharField(blank=True, help_text='Optional file ID of a Google Drive spreadsheet', max_length=250),
        ),
    ]
