# Generated by Django 4.1.9 on 2023-07-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontent', '0025_rename_last_update_log_cdeexplorerpage_update_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataset',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='santiagotaxonomypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='santiagotaxonomypage',
            name='taxonomy',
        ),
        migrations.RemoveField(
            model_name='treeexplorerpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='MetadataObject',
        ),
        migrations.DeleteModel(
            name='MetadataSet',
        ),
        migrations.DeleteModel(
            name='SantiagoTaxonomyPage',
        ),
        migrations.DeleteModel(
            name='TreeExplorerPage',
        ),
    ]
