# Generated by Django 4.1.9 on 2023-08-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontent', '0026_remove_metadataset_page_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdeexplorerattribute',
            name='inheritance',
            field=models.BooleanField(default=False, help_text='Attribute inherits values'),
        ),
    ]
