# Generated by Django 4.1.9 on 2023-08-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontent', '0028_referencesetsnippet_specimentypesnippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencesetsnippet',
            name='reference_set_code',
            field=models.CharField(help_text='Reference set ID code', max_length=80, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='specimentypesnippet',
            name='specimen_type_code',
            field=models.CharField(help_text='Specimen type ID code', max_length=80, primary_key=True, serialize=False, unique=True),
        ),
    ]
