# Generated by Django 4.1.9 on 2023-09-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrnsitecontent', '0030_alter_referencesetsnippet_reference_set_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdeexplorerobject',
            name='stewardship',
            field=models.TextField(blank=True, help_text="Who's responsible for this object"),
        ),
    ]
