# Generated by Django 4.2.20 on 2025-03-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edrnsitecontent", "0040_alter_flexpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cdeexplorerobject",
            name="page",
        ),
        migrations.RemoveField(
            model_name="cdeexplorerobject",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="cdeexplorerpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="cdepermissiblevalue",
            name="attribute",
        ),
        migrations.DeleteModel(
            name="CDEExplorerAttribute",
        ),
        migrations.DeleteModel(
            name="CDEExplorerObject",
        ),
        migrations.DeleteModel(
            name="CDEExplorerPage",
        ),
        migrations.DeleteModel(
            name="CDEPermissibleValue",
        ),
    ]
