# Generated by Django 5.2.11 on 2026-06-05 17:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edrnsitecontent", "0041_remove_cdeexplorerobject_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("cards", 4),
                    ("table", 5),
                    ("data_explorer", 9),
                    ("block_quote", 10),
                    ("typed_table", 16),
                    ("carousel", 22),
                    ("dashboard", 24),
                    ("raw_html", 25),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Richly formatted text",
                            "icon": "doc-full",
                            "label": "Rich Text",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title of this card, max 100 chars",
                            "max_length": 100,
                        },
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("title", 1)]], {}),
                    3: ("wagtail.blocks.ListBlock", (2,), {}),
                    4: ("wagtail.blocks.StructBlock", [[("cards", 3)]], {}),
                    5: ("edrnsite.streams.blocks.TableBlock", (), {}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Short alphanumeric ID for this block",
                            "max_length": 8,
                            "null": False,
                            "required": True,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title to display for this explorer block",
                            "max_length": 80,
                            "null": False,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "File ID of a Google Drive spreadsheet; don't forget to Update from Google Drive!",
                            "max_length": 60,
                            "null": False,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("block_id", 6), ("title", 7), ("spreadsheet_id", 8)]],
                        {},
                    ),
                    10: (
                        "edrnsite.streams.blocks.BlockQuoteBlock",
                        (),
                        {"help_text": "Block quote"},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Plain text cell"},
                    ),
                    12: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Rich text cell"},
                    ),
                    13: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {"help_text": "Numeric cell"},
                    ),
                    14: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Integer cell"},
                    ),
                    15: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Page within the site"},
                    ),
                    16: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [
                            [
                                ("text", 11),
                                ("rich_text", 12),
                                ("numeric", 13),
                                ("integer", 14),
                                ("page", 15),
                            ]
                        ],
                        {},
                    ),
                    17: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Overlaid label, if any",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Overlaid caption, if any",
                            "max_length": 400,
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 17), ("label", 18), ("caption", 19)]],
                        {},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: ("wagtail.blocks.StructBlock", [[("media", 21)]], {}),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "The Early Detection Research Network",
                            "help_text": "Title of the dashboard",
                            "max_length": 120,
                            "required": True,
                        },
                    ),
                    24: ("wagtail.blocks.StructBlock", [[("title", 23)]], {}),
                    25: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"help_text": "Raw HTML (use with care)"},
                    ),
                },
                null=True,
            ),
        ),
    ]
