# P5 Continous Integration
# ========================

---

name: P5 Continuous Integration

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'docs/**'

jobs:
    testing:
        name: P5 Testing
        runs-on: ubuntu-latest
        steps:
            -
                name: Checking out P5 repository
                uses: actions/checkout@v2
            -
                name: Running tests
                uses: ./.github/actions/buildout

    imaging:
        name: P5 Docker Image Creation
        runs-on: ubuntu-latest
        needs: testing
        steps:
            -
                name: Checking out P5 repository
                uses: actions/checkout@v2
            -
                name: Building image
                run: docker image build --file Dockerfile --tag edrn-p5 .


...
