# P5 Continous Integration
# ========================

---

name: P5 Continuous Integration

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'docs/**'

jobs:
    testing:
        name: P5 Testing
        runs-on: ubuntu-latest
        steps:
            -
                name: Checking out P5 repository
                uses: actions/checkout@v2
            -
                name: Building out P5 in dev mode
                uses: ./.github/actions/buildout
                with:
                    buildout-config: dev.cfg
            -
                name: Testing theme package `edrn.theme`
                run: bin/test -s edrn.theme
            -
                name: Testing policy package `edrnsite.portlets`
                run: bin/test -s edrnsite.policy
            -
                name: Testing portlets package `edrnsite.portlets`
                run: bin/test -s edrnsite.portlets
            -
                name: Testing knowledge environment `eke.knowledge`
                run: bin/test -s eke.knowledge
    imaging:
        name: P5 Docker Image Creation
        runs-on: ubuntu-latest
        needs: testing
        steps:
            -
                name: Checking out P5 repository
                uses: actions/checkout@v2
            -
                name: Building image
                run: docker image build --file Dockerfile --tag edrn-p5 .

...
