# P5 Continous Integration
# ========================

---

name: P5 Continuous Integration

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'docs/**'

jobs:
    testing:
        name: P5 Testing
        runs-on: ubuntu-latest
        steps:
            -
                name: Checking out P5 repository
                uses: actions/checkout@v2
            -
                name: Building out and testing P5
                uses: ./.github/actions/buildout-test
                with:
                    buildout-config: dev.cfg
                    test-packages: |
                        edrn.theme
                        edrnsite.policy
                        edrnsite.portlets
                        eke.knowledge
    imaging:
        name: P5 Docker Image Creation
        runs-on: ubuntu-latest
        needs: testing
        steps:
            -
                name: Checking out P5 repository
                uses: actions/checkout@v2
            -
                name: Building image
                run: docker image build --file Dockerfile --tag edrn-p5 .

...
